### ISSUE TITLE
Consolidating themes

### ISSUE THREAD

**Issue by dritter** [agnoster/agnoster-zsh-theme#1]
Hey @agnoster !

Do you see any chance of unifying the many "forks" into this one? Of course, these are no real forks, because your repo came a bit late. Anyway. Some of these themes have solved some of your as "future work" marked issues. So it may be a good thing to merge that work into one repo (or - in worst case - to let go in favour of another theme).
A while ago I made a list of powerline-inspired themes: [agnoster-like-themes](https://github.com/dritter/agnoster-like-themes).

**Comment by agnoster** [comment]
Yes, this is definitely a near-term goal! Ideally I'd like to backport useful features/additions from "forks" out there and bring as many people to the One Theme To Rule Them All. Key is allowing configuration without making it either a) complicated or b) slowing down themes that aren't using all the features.

**Comment by dritter** [comment]
Good to hear! :)

I like the idea to bring it all together in one place, but I am a bit biased on this, because I invested quite some time in the development of one of these forks, to achieve exactly that. I think at the end your theme would look like one of the forks (or be very similar).

Anyway. Don't listen to my grumpy me. I am exited what you come up with. I think I'll contribute one or another feature..
