### ISSUE TITLE
virtualenv support?

### ISSUE THREAD

**Issue by brianjking** [agnoster/agnoster-zsh-theme#10]
Is there a way to see if I'm working in a virtualenv when using Agnoster (Prezto & iTerm2 on OS X 10.11)?

**Comment by MichaelAquilina** [comment]
I had the same question and decided to fix it myself. Take a look at my pull request: https://github.com/agnoster/agnoster-zsh-theme/pull/11

**Comment by diraol** [comment]
I'm using the virtualenvwrapper plugin.
With it, I've added the following codes on `~/.virtualenvs/postactivate`:
```
PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
RPROMPT="%{${fg_bold[white]}%}(env: %{${fg[white]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"
```
And the following on `~/.virtuanenvs/postdeactivate`:
```
RPROMPT="$_OLD_RPROMPT"
```
With that I have a marker on the right side of the screen with the current virutalenv while I'm on the directory related to that venv. Something like: `(env: envName)` (right aligned)

**Comment by Cellophan** [comment]
Line 195, you'll find how to show have a virtualenv prompt:

    prompt_virtualenv() {
        local virtualenv_path="$VIRTUAL_ENV"
        if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]; then
            prompt_segment blue black "(`basename $virtualenv_path`)"
        fi
    }

If you set the variable VIRTUAL_ENV_DISABLE_PROMPT in your .zsh and virtualenv_path is correctly set, you'll have your virtiual env in your prompt.

**Comment by MichaelAquilina** [comment]
We can probably close this @agnoster . It has been supported for a while now

**Comment by apjanke** [comment]
Closing as Fixed.
