### ISSUE TITLE
MobaXterm theme colors not shoving & path problem

### ISSUE THREAD

**Issue by kjanezic95** [agnoster/agnoster-zsh-theme#100]
I am using MobaXterm terminal for Windows 10. I have tried using zsh + oh-my-zsh in two ways:
- Running zsh from default bash terminal -> i get colors, i cant use apt-get etc..
- Setting ZSH as default shell -> i dont get colors, apt-get works...

So does anyone know how to either fix paths or prompt colors in MobaXterm ZSH? If this is not possible I guess ill use windows linux subsystem and install ZSH + oh-my-zsh there and use trough that.

No colors, working apt-get
![t1](https://user-images.githubusercontent.com/33332006/52566797-f830a900-2e0a-11e9-848c-d45f46daeb67.PNG)

Colors, apt-get not working
![t2](https://user-images.githubusercontent.com/33332006/52566795-f830a900-2e0a-11e9-9f16-9a03c46e2757.PNG)

**Comment by apjanke** [comment]
This repo is the repo for the Agnoster theme, specifically. It does not look like you are using Agnoster here. Try asking this question in a more general Oh-My-Zsh forum, like the Oh-My-Zsh repo at https://github.com/ohmyzsh/ohmyzsh, or the #oh-my-zsh channel on Freenode IRC.
