### ISSUE TITLE
Not getting fonts working correctly in Konsole (cut in half, sorta)

### ISSUE THREAD

**Issue by markg85** [agnoster/agnoster-zsh-theme#102]
Hi,

I followed the examples on the main page and installed the powerline patched fonts.
When i run the echo line to test if everything works, i see:
https://i.imgur.com/TEcHjre.png

Right now the font i'm using is "Noto Mono for Powerline".

I did find issues in here that resemble the issue i have, but they are mostly for macOS. I'm on ArchLinux and using Konsole. I am using it like this (a bit broken visuals) for quite some time by now and figured i might need to figure this out :)

But i don't know what i might be doing wrong now.
Any help would be neat!

Cheers,
Mark

**Comment by apjanke** [comment]
This sounds like your terminal emulator is treating these characters as single-width characters, when in fact they are double-width. There may be an option in your terminal to do "Treat ambiguous-width characters as double-width" or something like that. Or you may need to update your terminal and text-handling libraries with support for a newer version of Unicode.

What version of Konsole are you using?

**Comment by markg85** [comment]
Nearly a year later...
Meanwhile, konsole has received some updates not long after i posted that issue. It apparently was known and is now with the current version not an issue anymore.

Thus closing this issue :)
