### ISSUE TITLE
Problem with \ue0b0 symbol

### ISSUE THREAD

**Issue by SergeyBrian** [agnoster/agnoster-zsh-theme#107]
Your theme worked perfectly before, but today it stopped displaying the \ue0b0 symbol correctly. Your test looks like that
![Screenshot from 2019-03-23 18-08-35](https://user-images.githubusercontent.com/42800290/54867895-fe655e00-4d96-11e9-98e3-a137449efcbe.png)

**Comment by chenqingze** [comment]
same issue
