### ISSUE TITLE
Getting "$(prompt_agnoster_main)" instead of cool-looking prompt

### ISSUE THREAD

**Issue by ridhwaans** [agnoster/agnoster-zsh-theme#113]
Using Mac, antigen, iTerm2  
In `.zshrc`, the theme doesnt work with these lines  

```
source $HOME/.zsh/bundle/bin/antigen.zsh
antigen theme https://github.com/agnoster/agnoster-zsh-theme
```  
example output 
``` 
Last login: Thu Jul 25 22:26:21 on ttys000
$(prompt_agnoster_main) cd ~
$(prompt_agnoster_main)

```
but changing these lines, the theme works  
```
source $HOME/.zsh/bundle/bin/antigen.zsh
antigen use oh-my-zsh # Load the oh-my-zsh's library.
antigen theme agnoster  
```    
does the theme not work without loading ohmyzsh

**Comment by qoomon** [comment]
See my PR #114 for the simple fix

**Comment by apjanke** [comment]
Do you have `setopt promptsubst` enabled? You need that.

**Comment by apjanke** [comment]
Closing as dupe of #35. Let's take the discussion over there and decide which fix approach is better.
