### ISSUE TITLE
My config in `~/.oh-my-zsh/themes/agnoster.zsh-theme` to random emoji.

### ISSUE THREAD

**Issue by emunozhern** [agnoster/agnoster-zsh-theme#116]
My config in `~/.oh-my-zsh/themes/agnoster.zsh-theme` to random emoji.
```zsh
prompt_context() {
  # Custom (Random emoji)
  emojis=("⚡️" "🔥" "💀" "👑" "😎" "🐸" "🐵" "🦄" "🌈" "🍻" "🚀" "💡" "🎉" "🔑" "🇹🇭" "🚦" "🌙")
  RAND_EMOJI_N=$(( $RANDOM % ${#emojis[@]} + 1))
  prompt_segment black default "${emojis[$RAND_EMOJI_N]} "
}
```

![image](https://user-images.githubusercontent.com/10693658/53974033-6af42200-4134-11e9-835b-7cc2d351bfe7.png)

_Originally posted by @biigpongsatorn in https://github.com/agnoster/agnoster-zsh-theme/issues/39#issuecomment-470603968_

**Comment by apjanke** [comment]
You can use "`local n`" instead of `$RAND_EMOJI_N` if you want to avoid clobbering variables set by the user or other code.

**Comment by apjanke** [comment]
FYI, I added this to [my AgnosterJ fork](https://github.com/apjanke/agnosterj-zsh-theme): https://github.com/apjanke/agnosterj-zsh-theme/commit/adb1be2a8c289317392b5dc004a0fdd527fefc16.
