### ISSUE TITLE
Show different Color for System Commands

### ISSUE THREAD

**Issue by RyanJiaxc** [agnoster/agnoster-zsh-theme#118]
I have successfully installed the theme and related fonts and plugins. The only issue I have is that my system commands (cd, ls, rm, etc) have the white color rather than a different color shown on the preview of this repo. What should I do to set a different color of system commands from normal texts?

**Comment by josesa** [comment]
This theme doesn't set that. Only the prompt where you type the commands.

Suggest to install prezto and https://github.com/sorin-ionescu/prezto/tree/master/modules/syntax-highlighting to have that feature but there are many others.

**Comment by apjanke** [comment]
Closed as not-an-Agnoster-issue.
