### ISSUE TITLE
Osx 10.15.1 - no green/red colorization of command

### ISSUE THREAD

**Issue by replay111** [agnoster/agnoster-zsh-theme#124]
When I am typing in cli ```git``` it does not have color green also if I type wrong command like ```git8``` this is not marked as red....

**Comment by apjanke** [comment]
I don't think this is something that Agnoster does. Maybe you were using a different program for command syntax colorization?

**Comment by belak** [comment]
I believe you're looking for something like https://github.com/zsh-users/zsh-syntax-highlighting or https://github.com/zdharma/fast-syntax-highlighting

**Comment by apjanke** [comment]
Yup. Closing as not-Agnoster-related.

**Comment by replay111** [comment]
YES! Thanks - I've seen some examples with Agnoster and this syntax highlight was present - I was sure that this is some Agnoster feature. Thanks!
