### ISSUE TITLE
Theme issue when using theme plugin

### ISSUE THREAD

**Issue by vaskark** [agnoster/agnoster-zsh-theme#126]
When changing themes using the theme plugin I encounter this:

![2019-12-28_04-52-05_PM](https://user-images.githubusercontent.com/33555080/71549886-325b5880-2993-11ea-9480-e4fd7ca5a39e.png)

The git branch is doubling-up. This does not happen when I set agnoster as my default theme in .zshrc.
Any help would be appreciated.
Thanks.

**Comment by apjanke** [comment]
What exactly do you mean by "the theme plugin" here?

**Comment by vaskark** [comment]
Ouch. Sorry. I meant the oh-my-zsh theme plugin.

**Comment by apjanke** [comment]
Oh, OMZ's `themes/agnoster.zsh-theme` plugin forked off from this Agnoster repo long ago. You need to go ask this [over there](https://github.com/ohmyzsh/ohmyzsh/issues), I think. Sorry!

**Comment by vaskark** [comment]
Double ouch! Thanks for letting me know.

**Comment by apjanke** [comment]
No prob. Good luck!
