### ISSUE TITLE
How to customize the prompt in oh-my-zsh?

### ISSUE THREAD

**Issue by SturmB** [agnoster/agnoster-zsh-theme#128]
I am still new to zsh, oh-my-zsh, and agnoster, as well as only an amateur with linux in general, so please bear with me.

I am loving the combination of the above, but have just one tiny issue with agnoster, summed up in the image below:

![mintty_D8ZkJAvkF1](https://user-images.githubusercontent.com/6216224/71745695-d54f1f00-2e38-11ea-8b7b-7567ae5fc351.png)

Is there any way to shorten the prompt to only show the current directory and not the entire absolute path to it? It makes the prompt far too huge for some of my work, as you can see.

Now, I am aware that you have a [Customize Your Prompt View](https://github.com/agnoster/agnoster-zsh-theme#customize-your-prompt-view) section in the README, but I'm still too new to understand how to use it to achieve the result I stated above. Also, I don't think it's geared for oh-my-zsh users, because when I run the first command listed in that section, `echo "${(F)AGNOSTER_PROMPT_SEGMENTS[@]}" | cat -n`, I get only a "1" with nothing next to it as a result.

What steps should I take to customize the agnoster prompt with oh-my-zsh?

**Comment by apjanke** [comment]
If you're using Agnoster under Oh My Zsh, you're actually running their fork of the Agnoster theme, and not the code from this repo. Please ask this over on the [Oh My Zsh repo](https://github.com/ohmyzsh/ohmyzsh); they may be able to help you.

This version of Agnoster does not currently support this. But there are some open PRs to add it in:
* https://github.com/agnoster/agnoster-zsh-theme/pull/71
* https://github.com/agnoster/agnoster-zsh-theme/pull/52
* https://github.com/agnoster/agnoster-zsh-theme/pull/17

**Comment by SturmB** [comment]
Although it probably isn't helpful to anyone else experiencing this issue, I've decided to try moving to [Powerlevel10k](https://github.com/romkatv/powerlevel10k). I'm quite pleased with it so far.

**Comment by hi20160616** [comment]
> Although it probably isn't helpful to anyone else experiencing this issue, I've decided to try moving to [Powerlevel10k](https://github.com/romkatv/powerlevel10k). I'm quite pleased with it so far.

Awesome project! easy and beautiful!
