### ISSUE TITLE
username@hostname Same background and foreground color

### ISSUE THREAD

**Issue by nmweizi** [agnoster/agnoster-zsh-theme#131]
After copying and pasting,can see username@hostname.
![图片](https://user-images.githubusercontent.com/1232444/73370194-cd2ab800-42ee-11ea-96dd-c39497c713fc.png)

- debian_version lsb_release -a
```
Distributor ID:	Debian
Description:	Debian GNU/Linux bullseye/sid
Release:	testing
Codename:	bullseye
```
- oh my zsh
```
origin/master
```
- zsh  version
```
5.7.1 (x86_64-debian-linux-gnu)
```
- .zshrc
```
ZSH_THEME="agnoster"
```
- echo $prompt     
``` 
%{%f%b%k%}$(build_prompt) 

```

**Comment by mcornella** [comment]
If you're using the OMZ version this issue can be closed.
