### ISSUE TITLE
I can't modify prompt segments

### ISSUE THREAD

**Issue by SandoDev** [agnoster/agnoster-zsh-theme#147]
I don't know what I'm doing wrong, but I can't modify my prompt segments.

something with environment variables?

the virtualenv prompt doesn't work for me either

i'm using [tilix](https://gnunn1.github.io/tilix-web/) as termianl

![Selection_025](https://user-images.githubusercontent.com/46248182/88207749-dcdbe700-cc15-11ea-8f2a-6e39a9d8b874.png)

**Comment by gshpychka** [comment]
Did you ever figure it out?

**Comment by SandoDev** [comment]
@gshpychka it has to do with the declaration of environment variables

but I could not solve it, and I changed to another theme 😬

I believe that the variable AGNOSTER_PROMPT_SEGMENTS is type array and must be declared in the system https://unix.stackexchange.com/questions/393091/unable-to-use-an-array-as-environment-variable

**Comment by dewafer** [comment]
FYI: https://github.com/agnoster/agnoster-zsh-theme/issues/97#issuecomment-552103087

**Comment by ehossack** [comment]
If you try #97, you might find an issue, so try #95 after....
