### ISSUE TITLE
Font not rendered correctly

### ISSUE THREAD

**Issue by paliitr** [agnoster/agnoster-zsh-theme#15]
![selection_001](https://cloud.githubusercontent.com/assets/10010419/19870720/cc36a3e0-9fd7-11e6-9be2-603708746044.png)

I am running Debian Jessie with Gnome 3.
The terminal is oh-my-zsh.
I also have the powerline fonts and font awesome installed. Earlier when I used Arch and Gnome 3, it worked fine. But I am not finding any solution to the issue.

**Comment by apjanke** [comment]
oh-my-zsh is not a terminal; it is a configuration framework for zsh. That's probably Gnome Terminal.

You may have an out of date version of the Powerline-patched fonts; that can cause this behavior. Try downloading the most recent version from the [powerline-fonts repo](https://github.com/powerline/fonts) and using those.

**Comment by paliitr** [comment]
Sorry for that terminal thing.

About the the latest powerline, I did install that from the github repo.

**Comment by apjanke** [comment]
Hmm. Not sure what to suggest then; sorry.

**Comment by paliitr** [comment]
Its ok. Thanks for helping.

**Comment by berkedel** [comment]
Have you tried setting your terminal font to Melso for Powerline?

**Comment by paliitr** [comment]
Nope @berkedel .

BDW the problem is solved. There was a problem with the font cache. I updated it and everything is working fine. @apjanke @berkedel

**Comment by JoseCage** [comment]
Hello @paliitr can you please share how you solved?

I have the same issue :bug: .

**Comment by JoseCage** [comment]
Sorry.. I solve this following the guides here: https://powerline.readthedocs.io/en/latest/installation/linux.html#font-installation

Thanks for all.. And @agnoster thanks for the theme.. :+1: :package:

**Comment by paliitr** [comment]
@JoseCage I just updated the font cache using
'font cache using fc-cache -vf ~/.fonts/`

**Comment by JoseCage** [comment]
As mentioned @paliitr I have already done this seconds before i commented here.. By the way thank you so much.. 

(And sorry for my english :us:)
