### ISSUE TITLE
Some identification characters cannot be displayed

### ISSUE THREAD

**Issue by forliuyifei** [agnoster/agnoster-zsh-theme#150]
![Screenshot_20201215-142418](https://user-images.githubusercontent.com/53306807/102178935-3f919000-3ee1-11eb-9b4b-99f19cfd417d.png)

Should I change specific font?

**Comment by waewoo** [comment]
Same problem...

**Comment by Geezgus** [comment]
https://medium.com/@cloverinks/oh-my-zsh-agnoster-theme-not-showing-correct-font-on-vscode-ubuntu-47b5e8dcbada

**Comment by forliuyifei** [comment]
Powerline font
