### ISSUE TITLE
Broken prompt after another oh-my-zsh upgrade

### ISSUE THREAD

**Issue by jorotg** [agnoster/agnoster-zsh-theme#155]
After anothe oh-my-zsh upgrade my prompt is messed up:

/Users/alabala1/.oh-my-zsh/themes/agnoster.zsh-theme:97: parse error near `<<<'
alabala1@ip-192-168-2-4 ~ %

```
prompt_context() {
<<<<<<< Updated upstream                                   < ---   line 97
  if [[ "$USERNAME" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)%n@%m"
=======
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
>>>>>>> Stashed changes
  fi
}
```

If I comment lines 97, 100 and 103 then I get:
/Users/alabala1/.oh-my-zsh/themes/agnoster.zsh-theme:108: parse error near `prompt_git'

```
prompt_git() {     <-- line 108
  (( $+commands[git] )) || return
  if [[ "$(git config --get oh-my-zsh.hide-status 2>/dev/null)" = 1 ]]; then
    return
  fi
  local PL_BRANCH_CHAR
  () {
    local LC_ALL="" LC_CTYPE="en_US.UTF-8"
    PL_BRANCH_CHAR=$'\ue0a0'         # 
  }
  local ref dirty mode repo_path
```

**Comment by HomyeeKing** [comment]
same here, looks like `git conflict` not be handled

**Comment by romanlex** [comment]
same issue

**Comment by tsterk** [comment]
I've got the same issue here.

**Comment by HaidongPang** [comment]
It seems to be a CRLF error.
Try this solution, it works.
```
cd $ZSH
git config core.autocrlf input
git rm --cached -r .
git reset --hard
```
Reference from:  [@sandyplus](https://github.com/ohmyzsh/ohmyzsh/issues/9781#issue-849694263)

**Comment by mcornella** [comment]
The agnoster theme in OMZ is not the same as this one. This should be an issue in OMZ, so you can close this one. Also, the proper way to make changes to a theme is to copy it in `$ZSH_CUSTOM` with the same name and modify it there: [full info here](https://github.com/ohmyzsh/ohmyzsh/wiki/Customization#overriding-and-adding-themes).

**Comment by Flexiboy** [comment]
> It seems to be a CRLF error.
> Try this solution, it works.
> 
> ```
> cd $ZSH
> git config core.autocrlf input
> git rm --cached -r .
> git reset --hard
> ```
> 
> Reference from: [@sandyplus](https://github.com/ohmyzsh/ohmyzsh/issues/9781#issue-849694263)

This worked partially for me. Yes it fixed the parse errors but I didn't got back the interface as you can see with the before/after screenshots below.

Before:
![Screen Shot 2021-04-14 at 6 36 31 PM](https://user-images.githubusercontent.com/56403567/114746766-62796700-9d50-11eb-9e33-9e35e9fd30cd.png)
After:
![Screen Shot 2021-04-14 at 6 36 43 PM](https://user-images.githubusercontent.com/56403567/114746770-6311fd80-9d50-11eb-82d3-b01d7ee50de0.png)
