### ISSUE TITLE
Set iTerm to use Meslo Font

### ISSUE THREAD

**Issue by jamesmcintyre** [agnoster/agnoster-zsh-theme#16]
I did a ton a troubleshooting only to realize that iterm needs to be using the meslo font so maybe it'd help to mention in main readme that it may be required in mac ox? Thanks!

**Comment by thunderer** [comment]
@jamesmcintyre It does not necessarily need to use Meslo, but you need to switch the desired font to its Powerline variant. I did that for my Ubuntu / ZSH / Terminator setup with Ubuntu Mono Powerline and it works perfectly.

**Comment by madsonic** [comment]
the readme mentions Menlo so it might be a bit confusing

**Comment by madsonic** [comment]
#25 the fix is here

**Comment by simPod** [comment]
TLDR https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-252443982

**Comment by apjanke** [comment]
This is now mentioned in the Agnoster [README under "Compatibility"](https://github.com/agnoster/agnoster-zsh-theme#compatibility).

Closing as fixed.

**Comment by apjanke** [comment]
Note for future users: New versions of iTerm now have built-in support for Powerline characters, so you can just go into the profile and turn on the check box for "use built-in Powerline glyphs" and then it'll work with any font.

See https://github.com/agnoster/agnoster-zsh-theme/issues/127.
