### ISSUE TITLE
Right arrow not in readme.md screenshot

### ISSUE THREAD

**Issue by thewinger** [agnoster/agnoster-zsh-theme#20]
Hi, 
My iTerm2 with agnoster is showing a right arrow in the left border that is not in the readme.md screenshot.

Anyone know how to disable it?

![screen shot 2016-12-06 at 11 51 50](https://cloud.githubusercontent.com/assets/121455/20923001/a65ea836-bbaa-11e6-9709-ec9aafa0de94.png)

**Comment by apjanke** [comment]
I think that's the prompt "mark". It can be controlled in iTerm's Preferences under Profiles > Terminal > Shell Integration > "Show mark indicators".

**Comment by thewinger** [comment]
@apjanke It worked!! Thank you very much
