### ISSUE TITLE
¿Cómo diablo instalo este tema en Debian?

### ISSUE THREAD

**Issue by hurta2yaisel** [agnoster/agnoster-zsh-theme#21]
¿Alguien me puede decir como diablos instalo y configuro este tema paso a paso para que me quede JUSTO como sale en la foto??

**Comment by Niceplace** [comment]
Hola !

Perdóname estoy usando Google Traductor pero my espanol es muy minimal.
Tristemente, el terminal con la foto es iTerm2 (Mac OSX).

Con debian, necesitará cambio el tema de tu terminal en el "Contextual Menu" (Edit -> Profile Preferences -> etiqueta "Colours" -> "Built-in schemes").

**Comment by annata83** [comment]
En debian instala powerline https://powerline.readthedocs.io/en/latest/installation/linux.html#font-installation reinicia y en .zshrc cambia el nombre de el theme a ZSH_THEME="agnoster"

**Comment by apjanke** [comment]
Looks like this has been handled! Please re-open if you're still having trouble.
