### ISSUE TITLE
My theme error, shows question mark symbol

### ISSUE THREAD

**Issue by rohmanhm** [agnoster/agnoster-zsh-theme#23]
Hi, can you help me? What's happen with my themes?

![image](https://cloud.githubusercontent.com/assets/7524911/21414222/0ea3ae78-c830-11e6-88b2-e669dd9296a8.png)

**Comment by rohmanhm** [comment]
Got the solutions 🍺
https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-252443982

**Comment by ghost** [comment]
For Mac Terminal : 

This need the Powerline fonts installed for the Mac, check here : https://github.com/powerline/fonts

Then if you find the colors to be little not suitable you can change in preferences > display > text > ANSI Colors (customise based on your vision)

After installation and customisation do not forget to restart the terminal, so that changes take effect on your terminal

**Comment by dabit3** [comment]
If it's April 2021 or later and you're still getting this issue, install the Fira Code Nerd Font as outlined in [these docs](https://starship.rs/faq/#what-is-the-configuration-used-in-the-demo-gif)

https://www.nerdfonts.com/font-downloads

**Comment by saberman** [comment]
> If it's April 2021 or later and you're still getting this issue, install the Fira Code Nerd Font as outlined in [these docs](https://starship.rs/faq/#what-is-the-configuration-used-in-the-demo-gif)
> 
> https://www.nerdfonts.com/font-downloads
This helped me a lot! Thanks!!!

**Comment by amirehsan** [comment]
> If it's April 2021 or later and you're still getting this issue, install the Fira Code Nerd Font as outlined in [these docs](https://starship.rs/faq/#what-is-the-configuration-used-in-the-demo-gif)
> 
> https://www.nerdfonts.com/font-downloads

This solved my problem. Thanks so much!

**Comment by EvanHerman** [comment]
@dabit3 Even with the Fira Code Nerd Font, I'm still having issues

**Edit:** I forgot I had created a custom username, and I was setting the font on the default. Once I switched to my username and updated the font, everything is working fine.

![image](https://user-images.githubusercontent.com/5321364/150021213-b9426597-b248-42f9-b65b-7c0eb1958374.png)

**Comment by bastulli** [comment]
Installing **'Fira Code Nerd Font'** from https://github.com/ryanoasis/nerd-fonts solved my issue.  Ubuntu users can just type **'sudo apt install fonts-firacode'**.  I also installed powerline fonts first but did not resolve seeing ? with Ubuntu WSL terminal

**Comment by yurimejia** [comment]
> If it's April 2021 or later and you're still getting this issue, install the Fira Code Nerd Font as outlined in [these docs](https://starship.rs/faq/#what-is-the-configuration-used-in-the-demo-gif)
> 
> https://www.nerdfonts.com/font-downloads

Indeed this comment helped, together with the instructions for installation and other tips in [configure terminal for data science with oh my zsh](https://engineeringfordatascience.com/posts/configure_terminal_for_data_science_with_oh_my_zsh/)

**Comment by rosmur** [comment]
Is it only the Fira Nerd Font that works? or any in the Nerd font family?
