### ISSUE TITLE
cant view the powerline symbols

### ISSUE THREAD

**Issue by MAGICCC** [agnoster/agnoster-zsh-theme#25]
Hi, 
I installed zsh/powerline via the install.sh but can't see the special git symbols. I am using Debian jessie

**Comment by AxelBriche** [comment]
Same on macos sierra.

**Comment by AxelBriche** [comment]
I have find the solution here:
https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-252443982

**Comment by JoacoRu** [comment]
this resolve to me. 
How to open the menu of the terminal ? "command +  , " (command + comma)
<img width="817" alt="Captura de Pantalla 2021-05-30 a la(s) 07 33 10" src="https://user-images.githubusercontent.com/16200773/120100879-8551b600-c119-11eb-9cc1-42ebf7b9796f.png">
