### ISSUE TITLE
Problem with Powerline symbols

### ISSUE THREAD

**Issue by azat-io** [agnoster/agnoster-zsh-theme#26]
![screenshot from 2017-01-19 20-23-24](https://cloud.githubusercontent.com/assets/5698350/22117501/530134c6-de85-11e6-9ba7-a4e76ce9b5e4.png)

Hello!

Please, look at the first line of the picture. It seems that all fonts works perfectly. So, why I can see big black circle in the "yellow" project folders?

**Comment by dritter** [comment]
Hi!

I assume you use the `agnoster.zsh-theme` from oh-my-zsh. This is slightly different from the one here. One of these differences is that black dot. It comes from [this](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/agnoster.zsh-theme#L122) line:
```zsh
zstyle ':vcs_info:*' unstagedstr '●'
```
If you have unstaged files in your repository, this dot informs you about this. So it's not a bug, it's a feature. ;)

**Comment by azat-io** [comment]
@dritter Wow. Thank you for your help. Black dot looks ugly
