### ISSUE TITLE
docs: how to set up things to have commands in color

### ISSUE THREAD

**Issue by pascalpoizat** [agnoster/agnoster-zsh-theme#32]
The commands do not appear to be in color as in the screenshots (eg `cd` in the first line of the screen shot).

Is there some configuration I have missed?
(anyway, a great thanks for the fantastic theme)

![capture d ecran 2017-03-03 a 15 04 51](https://cloud.githubusercontent.com/assets/6471971/23553843/cda2523c-0022-11e7-8840-ba3b0bf8da14.png)

**Comment by cpsxhao** [comment]
Try to use the zsh-syntax-highlighting.
https://github.com/zsh-users/zsh-syntax-highlighting

**Comment by pascalpoizat** [comment]
Thank you @cpsxhao it works well.
Under OSX I did:
1. `brew install zsh-syntax-highlighting`
2. edited my $HOME/.zshrc file, adding a reference to zsh-syntax-highlighting after the loading of other plugins as recommended.
```
...
... # lots of things
...
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git github osx)

source $ZSH/oh-my-zsh.sh

# **NEW**
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# User configuration
...
...
```
