### ISSUE TITLE
character formatting is changed

### ISSUE THREAD

**Issue by mustafaozhan** [agnoster/agnoster-zsh-theme#38]
Hello everything worked fine but i released that something changed in my terminal i don't know it is about me or issue right now i am getting this characters, when i write 
echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699"
![image](https://cloud.githubusercontent.com/assets/21145590/25918303/9ed65ee4-35d3-11e7-83c8-c945365a9c02.png)

**Comment by Kleinast** [comment]
Hello, 
I just install zsh and activate agnoster-zsh-theme, and I think I have similar problem.
I normally installed Powerline fonts and I got that:

![capture du 2017-05-22 10-00-57](https://cloud.githubusercontent.com/assets/2306947/26304133/7e2ab3b4-3eea-11e7-8fb1-51e4cc8c1fef.png)

Icon appear when I write echo "\ue0b0 \u00b1 \ue0a0 \u27a6 \u2718 \u26a1 \u2699" but the point of colored arrow not appear normaly.

Is it me or a bug ?

Thx

**Comment by suraj94mec** [comment]
Hi,
I too just ran into the same issue. I got it fixed from this reference
[https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-275733922](url)

**Comment by mustafaozhan** [comment]
I got solution after installing python-powerline. So that's means i removed somehow by mistake than it seems like that. Now everything is okey

**Comment by Kleinast** [comment]
Hi

your link @suraj94mec seem to lead to a 404 page.
Thx you @mustafaozhan I will try tomorrow and tell you if that fix my problem as well

**Comment by suraj94mec** [comment]
@Kleinast 
i have updated the link

**Comment by Kleinast** [comment]
Thx @suraj94mec, you and your link help me fix my problem, just have to change font in my ubuntu terminal profil.
