### ISSUE TITLE
Problem with Theme

### ISSUE THREAD

**Issue by wasudev** [agnoster/agnoster-zsh-theme#41]
My terminal
![screen shot 2017-06-16 at 4 47 40 pm](https://user-images.githubusercontent.com/15046290/27221794-09c9856c-52b4-11e7-85d2-b5658cb5b3b4.png)

I want this
![70f58fb6-ba03-11e4-82c9-c083bf9a6574](https://user-images.githubusercontent.com/15046290/27221826-1f9b346c-52b4-11e7-8cd0-e212d7df4a0e.png)

How to fix it?

**Comment by DanielBiegler** [comment]
You can change the colours by hand in the settings file (probably) located in `.oh-my-zsh/themes/agnoster.zsh-theme` to fit your needs.

**Comment by Aktariel** [comment]
Try also iTerm 2 and the solarized colorscheme (you can change the colors that the values map to in your termina emulator). And be sure to disable the portions of the prompt that you don't need!

**Comment by apjanke** [comment]
Looks like you're using a different font, too. To me, the font in the "I want this" screenshot looks like Menlo or Meslo running on a non-retina display.
