### ISSUE TITLE
My Shell is returning some unknown characters

### ISSUE THREAD

**Issue by miraclx** [agnoster/agnoster-zsh-theme#48]
I decided to give agnoster a try and it shows the other stuff but doesnt show the output shown in the md image
![IMAGE](https://user-images.githubusercontent.com/16881812/29984051-6f276450-8f50-11e7-90d0-fdd5f08ad4b5.png)
**NEVER MIND** ITS BEEN SOLVED

**Comment by francklafon** [comment]
Hi Miraclx, how to repair this ? Thanks you  ! :)

**Comment by miraclx** [comment]
Install this and select one of the fonts for your terminal
https://github.com/powerline/fonts

I chose NovaMonoForPowerline

There's also a Ubuntu mod for it

- Miraclx
