### ISSUE TITLE
Opening the terminal I see a red cross, how to remove it?

### ISSUE THREAD

**Issue by gHashTag** [agnoster/agnoster-zsh-theme#54]
Opening the terminal I see a red cross, how to remove it after open iTerm2?
![2017-09-29 19 18 02](https://user-images.githubusercontent.com/6774813/31025331-f090640a-a54a-11e7-9a37-7ce623a1229e.png)

**Comment by nfanta** [comment]
Hi, @gHashTag the cross means that the last command exited with a non-zero status. Could it be that there's something in your `.zshrc` file that's causing it?

**Comment by gHashTag** [comment]
Yes, It was necessary to fulfill this paragraph:
https://gist.github.com/kevin-smets/8568070#syntax-highlighting

**Comment by isinaltinkaya** [comment]
so what is the solution? removing syntax-highlighting?

**Comment by Zaheer-A** [comment]
I am having the same issue now. Could you share the solution?

**Comment by centurion6x** [comment]
I'm having it now. although the last command was successful.

**Comment by hans0l0** [comment]
> Opening the terminal I see a red cross, how to remove it after open iTerm2?
> ![2017-09-29 19 18 02](https://user-images.githubusercontent.com/6774813/31025331-f090640a-a54a-11e7-9a37-7ce623a1229e.png)

my iterm2 wanted to check if the shell integrations were present and was testing it at the end of .zshrc.  Fixed it by iTerm menu -> Install Shell Integration
