### ISSUE TITLE
Color/alignment is off

### ISSUE THREAD

**Issue by blfang** [agnoster/agnoster-zsh-theme#55]
<img width="397" alt="screen shot 2017-10-02 at 11 54 35" src="https://user-images.githubusercontent.com/1924485/31094037-8bc12e22-a768-11e7-85e1-604da1e7b62b.png">

[Ignore the censored directory name.] For some reason the colors and alignment of the tip of each color block is slightly off. It was fine before, but I did not realize when exactly this changed, so I am not sure what the cause is. I tried to change other settings (font, color), but could not get the colors/alignment to go back to normal. Currently I am using the solarized dark color theme in iTerm2 with the Input Mono Narrow font; previously I used Monaco, but changing it back does not fix it. Does anyone recognize these two issues (color and alignment)?

Thanks!

**Comment by rggvn** [comment]
just started using this theme and ran into the same problem. Fixed it by giving the window no transparency

**Comment by lgraubner** [comment]
Also try to set the Minimum contrast slider to the left (can be found in Settings->Profiles->Colors). That worked for me.

**Comment by blfang** [comment]
Thanks @rggvn and @lgraubner ! Both the transparency and minimum contrast affect the color, and your suggestions fix the issue.

Regarding the alignment of the triangular tip with the rest of the color block on the left, I found that it is a font issue. It aligns well with 12pt Monaco, but with other font sizes and font faces, the alignment will not be great. I suppose this is to be expected.

**Comment by griiid** [comment]
You can use window transparency, but let "Keep background colors opaque" being checked, its right below Window Appearance Transparency (Settings->Profiles->Window)
