### ISSUE TITLE
Circle and question mark icons after the git branch?

### ISSUE THREAD

**Issue by monsonjeremy** [agnoster/agnoster-zsh-theme#62]
I just installed oh-my-zsh and set the theme to agnoster and am seeing a weird circle icon and a question mark icon following my git branch. Does anyone know what these are or how i can remove them?
![screen shot 2017-12-11 at 11 58 27](https://user-images.githubusercontent.com/8846086/33860861-a98a7310-de8f-11e7-880f-678d078e5e05.png)

**Comment by youhackme** [comment]
Getting the same issue here. Anyone with a solution?

**Update:**

Found the issue. Was using the powerlevel9 theme. Switched to agnoster theme, it worked! Here's how to change theme:


1. nano  `~/.zshrc `
2. Change current theme to this:  ZSH_THEME="agnoster"

**Comment by apjanke** [comment]
Closing because fix was reported.

@monsonjeremy - if you're still having this problem, please re-open this issue, and let us know what OS and terminal emulator you're using.

**Comment by rubystar** [comment]
<img width="722" alt="Screenshot 2021-01-17 at 10 59 15 PM" src="https://user-images.githubusercontent.com/1391377/104850870-a27aaa80-5917-11eb-83ea-e781d7cc53a0.png">

Hey i'm seeing the question mark. Changing the theme to agnoster didn't solve it for me. Any suggestions please?

**Comment by rarspace01** [comment]
This can be from your git zsh plugin. the ?4 can stands for 4 untracked files:
` ~/git/m/m  sourcing ?2  git status                               INT ✘  2.5.1 
On branch sourcing
Your branch is up to date with 'origin/sourcing'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	buildSrc/
	gradle/

nothing added to commit but untracked files present (use "git add" to track)`
