### ISSUE TITLE
on ubuntu latest I see diamond

### ISSUE THREAD

**Issue by cybermerlin** [agnoster/agnoster-zsh-theme#63]
I use git clone powerline fonts and fc-cahe -vf after installation but this is not helped me.

help me please

**Comment by apjanke** [comment]
Closing as moot because it's 2 years old.

If you're still having this issue, please re-open and let us know what version of Ubuntu you're running (version number, not "latest") and if you can, include a screenshot of what you're seeing that looks wrong.
