### ISSUE TITLE
I would like to have the command line in next line how do I do that?

### ISSUE THREAD

**Issue by shiroamada** [agnoster/agnoster-zsh-theme#65]
I love the color scheme, but sometimes my git branch name kind of too long, it make me hard to read what I type.
How do I make like below
shiro@Mac  ~/Sites/myproject/test/project1   branch-new-feature ● 
> my command start here

**Comment by griiid** [comment]
Hi, u can edit `agnoster.zsh-theme`

- search `prompt_end()`
- modify `print -n "%{%f%}"` as `print -n "\n%{%f%}"` (just add `\n` )
- save it and re-open ur terminal

**Comment by shiroamada** [comment]
Hi may I know where is agnoster.zsh-theme located?

**Comment by griiid** [comment]
Maybe u can find it in this path: ` ~/.oh-my-zsh/custom/themes/`  or `~/.oh-my-zsh/themes`  
I'm not really sure.

**Comment by shiroamada** [comment]
Thanks @Griiid !

**Comment by jamesg1** [comment]
Cheers @Griiid !!

**Comment by Nagha51** [comment]
Many thanks <3 ! @Griiid

**Comment by paul1994** [comment]
Thanks @Griiid ! Something this simple is not always that obvious.

**Comment by nickBlack4** [comment]
~/.oh-my-zsh/themes/agnoster.zsh-theme

**Comment by cristianMeli** [comment]
> Hi, u can edit `agnoster.zsh-theme`
> 
> * search `prompt_end()`
> * modify `print -n "%{%f%}"` as `print -n "\n%{%f%}"` (just add `\n` )
> * save it and re-open ur terminal

Thank you!

**Comment by uyo-obong** [comment]
> Hi, u can edit `agnoster.zsh-theme`
> 
> * search `prompt_end()`
> * modify `print -n "%{%f%}"` as `print -n "\n%{%f%}"` (just add `\n` )
> * save it and re-open ur terminal

Thanks buddy. 

in case you don't see print again in agnoster, they have change to echo, so you will modify like this
`echo -n "\n%{%f%}"`

**Comment by daveseco7** [comment]
Thanks @Griiid 😄

**Comment by M1ke** [comment]
I've carried this out and additionally added a little prompt because it felt better `echo -n "\n>%{%f%}"` so it places a `>` character on the newline before the cursor. However that character inherits the colour of whatever the main prompt line ends with (e.g. blue for directories, green or yellow for git). Is there a way I can force it to always be white?

**Comment by griiid** [comment]
> I've carried this out and additionally added a little prompt because it felt better `echo -n "\n>%{%f%}"` so it places a `>` character on the newline before the cursor. However that character inherits the colour of whatever the main prompt line ends with (e.g. blue for directories, green or yellow for git). Is there a way I can force it to always be white?

Hi @M1ke, you can use this: `echo -n "\e[m\n>%{%f%}"`

which added `\e[m` before `\n`

**Comment by WencesLlobet** [comment]
*If you are not seeing any change* maybe you are using the '**robyrussell**' theme (it was my default). You can check that at the beginning of .zshrc:
If that is your case substitute this line in the file  ~/oh-my-zsh/themes/robbyrussell.zsh-theme : 
`PROMPT+=' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)'`
for this one.
`PROMPT+=$' %{$fg[cyan]%}%c%{$reset_color%} $(git_prompt_info)\n'`

We sometimes get tired of configuring many times all the linux set up, for that reason you can move the config fimes .vimrc .zshrc ... to a repo, commit them often and make the system reach them at that place by creating hard links.

**Comment by harsh-singh-rathore** [comment]
> Hi, u can edit `agnoster.zsh-theme`
> 
>     * search `prompt_end()`
> 
>     * modify `print -n "%{%f%}"` as `print -n "\n%{%f%}"` (just add `\n` )
> 
>     * save it and re-open ur terminal

I did this procedure and it works fine but many times my zsh misbehaves in a random way.
Some times while I'm typing the first letter just vanishes and the virual thing just messes up if you guys are also facing this problem how did you all solve this?

**Comment by SwiftWinds** [comment]
Does anyone get this visual issue or know how to solve it?:

![image](https://user-images.githubusercontent.com/12981958/97753189-97e80c00-1ab2-11eb-9f40-b8ef414ac44a.png)

My `prompt_end()`:

```bash
# End the prompt, closing any open segments
prompt_end() {
  if [[ -n $CURRENT_BG ]]; then
    echo -n " %{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
  else
    echo -n "%{%k%}"
  fi
  CURRENT_BG=''
  echo -n "\e[m\n➜%{%f%}"
}
```

**Comment by zorzysty** [comment]
> 
> 
> Does anyone get this visual issue or know how to solve it?:
> 
> ![image](https://user-images.githubusercontent.com/12981958/97753189-97e80c00-1ab2-11eb-9f40-b8ef414ac44a.png)

A bit late to the party, but if anybody else is experiencing the above, I've replaced the last two lines and it seems to be working fine:
```bash
  echo -n "\e[m\n➜%{%f%}"
  CURRENT_BG=''
}  
```

**Comment by Emily-Herndon** [comment]
So I'm currently using af-magic and I like the look but I hate how it's all on the initial line and cuts things off to go to the next line. I tried adding 
`prompt_end() {
if [[ -n $CURRENT_BG ]]; then
    echo -n " %{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
  else
    echo -n "%{%k%}"
  fi
  echo -n "\n%{%f%}"
  CURRENT_BG=''
}`
from agnoster but I don't see a difference. Is there something else I need to add or am I going about this totally wrong?

**Comment by M1ke** [comment]
> > I've carried this out and additionally added a little prompt because it felt better `echo -n "\n>%{%f%}"` so it places a `>` character on the newline before the cursor. However that character inherits the colour of whatever the main prompt line ends with (e.g. blue for directories, green or yellow for git). Is there a way I can force it to always be white?
> 
> Hi @M1ke, you can use this: `echo -n "\e[m\n>%{%f%}"`
> 
> which added `\e[m` before `\n`

I am 3 years late to addressing this, but thanks, have done this and it worked!

**Comment by ghost** [comment]
@Griiid Thanks griid

**Comment by GandharvJainSchrodinger** [comment]
> > Does anyone get this visual issue or know how to solve it?:
> > ![image](https://user-images.githubusercontent.com/12981958/97753189-97e80c00-1ab2-11eb-9f40-b8ef414ac44a.png)
> 
> A bit late to the party, but if anybody else is experiencing the above, I've replaced the last two lines and it seems to be working fine:
> 
>   echo -n "\e[m\n➜%{%f%}"
>   CURRENT_BG=''
> }

This didn't work for me so I looked into https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html#Visual-effects and found %E clears till end of line. Here's the fix:
```bash
  echo -n "%E\n$%{%f%}"
  CURRENT_BG=''
```
