### ISSUE TITLE
Multiple prompt messages are added indefinitely

### ISSUE THREAD

**Issue by bastienlabelle** [agnoster/agnoster-zsh-theme#73]
Hi there,

I'm having an issue with the theme. It used to work perfectly fine until yesterday, but today I had this very weird display: every time I hit enter to perform a command, the login@hostname is displayed again and again in the prompt.

Also, the first time the login@hostname is displayed at the beginning, it looks like a standard prompt (see image here: https://bstn.fr/agnoster.png )

I haven't modified any file, and other themes seems to work just fine.

Any chance anyone knows what's going on?

Thanks

**Comment by apjanke** [comment]
Hi there. The image you link to is 404; maybe that's on an image-sharing service where stuff expires?

If you're still having this problem, could you attach a screenshot in this GitHub issue itself? (Just drag the file on to the editing area to upload it.)
