### ISSUE TITLE
Some fonts aren't displayed properly on Mac

### ISSUE THREAD

**Issue by idanhaviv** [agnoster/agnoster-zsh-theme#76]
I use ITerm2, installed  Powerline-patched font but get this:
![image](https://user-images.githubusercontent.com/8762573/40966071-2dbf3e74-68b8-11e8-832e-8f4100f95fa2.png)

**Comment by dsoegijono** [comment]
~I'm seeing the same issue after a clean install.~

@idanhaviv Have you tried going to iTerm2's preferences > Profiles > Text and change the font to a Powerline font? That fixed it for me.

**Comment by idanhaviv** [comment]
@dsoegijono That's what I was missing. thanks!

**Comment by simPod** [comment]
https://github.com/robbyrussell/oh-my-zsh/issues/1906#issuecomment-252443982
