### ISSUE TITLE
How can I show the last (1 or 2) path instead of full directory?

### ISSUE THREAD

**Issue by dsoegijono** [agnoster/agnoster-zsh-theme#77]
Instead of `~/User/Documents/folder1/folder2`, I'd like to be able to just show `/folder2` or maybe `/folder1/folder2` so it doesn't take too much space. Is there a way for me to do this?

I'm looking at this section:
```
prompt_dir() {
  prompt_segment blue black '%~'
}
```

but I don't really understand what it means.

**Comment by apjanke** [comment]
See the "Shell State" section of the [Prompt Expansion](http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html) page in the Zsh reference manual.

You can stick a number between the `%` and `~` to limit the number of trailing path elements that are displayed. So, you could do:

```
  prompt_segment blue black '%2~'
```

to get the last two elements of the current directory.

See also the [`prompt-pwd` function in Prezto](https://github.com/sorin-ionescu/prezto/blob/master/modules/prompt/functions/prompt-pwd). It does more advanced prompt "compaction", abbreviating all but the last path element with a single letter, so you still have more context about where you are.

**Comment by dsoegijono** [comment]
Thanks for the explanation @apjanke!

**Comment by ahmed-hdeawy** [comment]
step 1. open your `.zshrc` file by `vim .zshrc`

step 2. go to the end of your file.

Paste this code:

```
prompt_dir() {
  prompt_segment blue $CURRENT_FG '%c'
}
```
