### ISSUE TITLE
unreadable text with cd [tab]

### ISSUE THREAD

**Issue by ashishmh** [agnoster/agnoster-zsh-theme#78]
when doing cd with tab to show various options, the options are not readable due to the color scheme. see attached screenshot.
<img width="764" alt="screen shot 2018-05-08 at 4 08 15 pm" src="https://user-images.githubusercontent.com/5380885/41098442-016bfa16-6a79-11e8-859a-f61e96736192.png">

**Comment by apjanke** [comment]
I don't think Agnoster enables colorization of the things displayed in tab completion menus. Do you have other Zsh customizers like Oh My Zsh or Prezto running?

**Comment by ashishmh** [comment]
I don't think i installed Prezto, but Oh My Zsh is there.

**Comment by ashishmh** [comment]
Update: I don't know when I reinstalled everything. But the color scheme is readable in tab completion menu now.
<img width="651" alt="Screen Shot 2020-01-04 at 4 32 12 PM" src="https://user-images.githubusercontent.com/5380885/71764612-eb7bde80-2f0f-11ea-95da-90e2fec8ac84.png">
