### ISSUE TITLE
How to add new line?

### ISSUE THREAD

**Issue by shakib609** [agnoster/agnoster-zsh-theme#8]
Hello, I'm trying to edit the theme to add a new line after the directory listings..

More like:

   ~/github/agnoster-zsh-theme >  master >
   my command here

I am trying to customize the theme. Can you help me out here?

**Comment by mcornella** [comment]
There are a number of modifications of the agnoster theme that put a newline, if you search `agnoster newline` you'll find plenty. 

What it all comes down to, though, is putting an `echo` at the end of the `prompt_build` function, if you look at the code you'll know what I mean.

**Comment by shakib609** [comment]
Thanks for the info.. :+1:  Closing this issue then. :)
