### ISSUE TITLE
strange look

### ISSUE THREAD

**Issue by RachadAbiChahine** [agnoster/agnoster-zsh-theme#81]
![image](https://user-images.githubusercontent.com/13370993/43418274-ada3e8be-943d-11e8-9387-534d0fe789c2.png)

**Comment by Eisfunke** [comment]
Seems like the font you're using doesn't support the necessary characters. Look at the [README](https://github.com/agnoster/agnoster-zsh-theme#compatibility).

**Comment by marzsv** [comment]
I have the same problem, I assumed that installing the powerline fonts it should work, but no... still doesn't work. Should I select a font somewhere or set it in my .zshrc ?

**Comment by Eisfunke** [comment]
> I have the same problem, I assumed that installing the powerline fonts it should work, but no... still doesn't work. Should I select a font somewhere or set it in my .zshrc ?

You have to select the powerline-supporting font in the terminal app you're using.

**Comment by liudonghua123** [comment]
I have the same issue, and I changed the terminal font which named end with `powerline`, then it works.

**Comment by apjanke** [comment]
Good old missing-powerline-fonts problem. Closing as fixed/dupe.
