### ISSUE TITLE
problems when trying to add terraform workspace 

### ISSUE THREAD

**Issue by yogeek** [agnoster/agnoster-zsh-theme#88]
As I did not understand how to integrate the terraform workspace in my prompt as explained here: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/terraform, I am trying to add it in my oh-my-zsh prompt by adding these lines to the ` ~/.oh-my-zsh/themes/agnoster.zsh-theme` file :

```
# other prompt stuff...

# Add terraform workspace in prompt when needed 
prompt_terraform() {
	if [[ -d .terraform ]]; then
	  local workspace=`terraform workspace show 2> /dev/null`
	  prompt_segment red black 
    	  echo -n "--->$workspace"
	fi
}

## Main prompt
build_prompt() {
  RETVAL=$?
  prompt_status
  prompt_virtualenv
  prompt_context
  prompt_dir
  prompt_git
  prompt_bzr
  prompt_hg
  prompt_terraform
  prompt_end
}

PROMPT='%{%f%b%k%}$(build_prompt) '
``` 

but I have the following problems :

- with simple `echo`, a newline is add after workspace :
```
 user@myvm  ~/terraform-project   master ●  --->staging
  
```
- with `echo -n`, only the prompt_end is displayed (all others prompt elements disappeared)
```
  
```

I tested to replace the `echo -n "--->$workspace"` by `echo -n "--->test"` or by `echo -n "--->$(pwd)"` and it works correctly but not with the result of the terraform command...

Did anyone succeed to use it please ?

**Comment by apjanke** [comment]
This repo is for the Agnoster theme only. The code in your post does not look like code from the Agnoster theme. It sounds like you're asking about RobbyRussell or one of the other themes included with Oh-My-Zsh. Please direct this question to the oh-my-zsh repo at https://github.com/ohmyzsh/ohmyzsh, or the #oh-my-zsh channel on Freenode IRC.
