### ISSUE TITLE
AGNOSTER_PROMPT_SEGMENTS does nothing

### ISSUE THREAD

**Issue by SheinH** [agnoster/agnoster-zsh-theme#97]
![iTerm](https://i.imgur.com/xkmNV9g.png)

I set my agnoster prompt segments in my `.zshrc` file but it appears to do nothing.
What could be the problem?

EDIT: The problem was oh-my zsh which had an outdated version of agnoster.

**Comment by SheinH** [comment]
Seems that my version was out of date. please close this issue.

**Comment by xiaoyaoyang** [comment]
hmm I have similar issues.. my out put looks like
![image](https://user-images.githubusercontent.com/6519744/67594216-d9243e00-f731-11e9-9bfd-906b656b0bb5.png)

**Comment by prurph** [comment]
I have the same issue as @xiaoyaoyang.

**Comment by prurph** [comment]
Updating to say the issue in my case I was using the version from [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) which is outdated. One quick hack to fix this is simply to overwrite the contents of [agnoster.zsh-theme](https://raw.githubusercontent.com/agnoster/agnoster-zsh-theme/master/agnoster.zsh-theme) in your oh-my-zsh themes directory (`~/.oh-my-zsh/themes/` by default) with the latest version from this repo and open a new shell. @xiaoyaoyang this will probably fix your issue as well.

You could also [add it as a custom theme](https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-themes) to avoid it getting reverted should you update oh-my-zsh.

**Comment by apjanke** [comment]
Issue closed per @SheinH's request.
